### ISSUE TITLE
[1.3.0] Installation of Weapon Changes component fails due to parse error

### ISSUE THREAD

**Issue by Doomathon** [BartyMae/IR_Revised#10]
Brief problem statement:
I was installing mods on a new installation of BGEE, and saw the Gibberlings 3 forum thread had mentioned a new version. Very nice!...the install process halts due to an error. Not so nice.

contents of the debug file: https://pastebin.com/2X0D83g4

From a glance at the file and line number it mentions (weapon_changes.tpa and line 714), it appears that when adding a few additional types of ammo to receive a +5 to hit bonus, the new lines all forgot to include ||, because it successfully installed when I edited the file to add them and tried again.

**Comment by BartyMae** [comment]
Dang it, I tested the main component, but not weapon changes. Tsk, tsk. Thank you, it's been fixed.
