### ISSUE TITLE
ERROR Installing [Item Revisions by Demivrgvs]

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/IR_Revised#12]
WeiDU v 24700 Log

 setup-item_rev.exe
[.\CHITIN.KEY] loaded, 648227 bytes
[.\CHITIN.KEY] 252 BIFFs, 45763 resources
[./Autorun.ini] loaded, 1452 bytes
[./baldur.ini] loaded, 3063 bytes
Possible HD/CD Path: [C:\BWP\BGII - SoA\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD1\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD2\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD2\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD3\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD4\]
Possible HD/CD Path: [C:\BWP\BGII - SoA\CD5\]
[./Keymap.ini] loaded, 5615 bytes
[./Mplaynow.ini] loaded, 230 bytes
[.\dialog.tlk] loaded, 14002128 bytes
[.\dialog.tlk] 112225 string entries
Using Language [English]
[English] has 2 top-level TRA files
[item_rev/languages/english/setup.tra] has 60 translation strings
[item_rev/languages/english/description_updates.tra] has 173 translation strings

Would you like to display the readme? [Y]es [N]o
TOBEX/TOBEX.TP2  0 100 Installed
TOBEX/TOBEX.TP2  0 101 Installed
TOBEX/TOBEX.TP2  0 102 Installed
TOBEX/TOBEX.TP2  0 105 Installed
TOBEX/TOBEX.TP2  0 109 Installed
TOBEX/TOBEX.TP2  0 111 Installed
TOBEX/TOBEX.TP2  0 113 Installed
TOBEX/TOBEX.TP2  0 114 Installed
TOBEX/TOBEX.TP2  0 115 Installed
TOBEX/TOBEX.TP2  0 116 Installed
TOBEX/TOBEX.TP2  0 117 Installed
TOBEX/TOBEX.TP2  0 118 Installed
TOBEX/TOBEX.TP2  0 119 Installed
TOBEX/TOBEX.TP2  0 120 Installed
TOBEX/TOBEX.TP2  0 121 Installed
TOBEX/TOBEX.TP2  0 122 Installed
TOBEX/TOBEX.TP2  0 123 Installed
TOBEX/TOBEX.TP2  0 124 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  0 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 1001 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  3 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 101 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 103 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 110 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 111 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 112 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 113 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 116 Installed
BGT/BGT.TP2  0  0 Installed
BGGRAPHICS/SETUP-BGGRAPHICS.TP2  0  0 Installed
RES_FIXER/SETUP-RES_FIXER.TP2  0  0 Installed
DSOTSC/DSOTSC.TP2  0  0 Installed
DSOTSC/DSOTSC.TP2  0  3 Installed
NTOTSC/NTOTSC.TP2  0  0 Installed
NTOTSC/NTOTSC.TP2  0  2 Installed
NTOTSC/NTOTSC.TP2  0  3 Installed
NTOTSC/NTOTSC.TP2  0  4 Installed
NTOTSC/NTOTSC.TP2  0  5 Installed
NTOTSC/NTOTSC.TP2  0  6 Installed
NTOTSC/NTOTSC.TP2  0  9 Installed
BGQE/SETUP-BGQE.TP2  0  0 Installed
BGQE/SETUP-BGQE.TP2  0  1 Installed
BGQE/SETUP-BGQE.TP2  0  2 Installed
BGQE/SETUP-BGQE.TP2  0  3 Installed
BGQE/SETUP-BGQE.TP2  0  4 Installed
BGQE/SETUP-BGQE.TP2  0  5 Installed
BGQE/SETUP-BGQE.TP2  0  6 Installed
BGQE/SETUP-BGQE.TP2  0  7 Installed
BGQE/SETUP-BGQE.TP2  0  8 Installed
BGQE/SETUP-BGQE.TP2  0  9 Installed
BGQE/SETUP-BGQE.TP2  0 10 Installed
BGQE/SETUP-BGQE.TP2  0 11 Installed
BGQE/SETUP-BGQE.TP2  0 12 Installed
BGQE/SETUP-BGQE.TP2  0 13 Installed
BGQE/SETUP-BGQE.TP2  0 14 Installed
BGQE/SETUP-BGQE.TP2  0 15 Installed
BGQE/SETUP-BGQE.TP2  0 16 Installed
SETUP-TGC1E.TP2  0  0 Installed
SIRINESCALL/SETUP-SIRINESCALL.TP2  0  0 Installed
SOA/SETUP-SOA.TP2  0  1 Installed
AC_QUEST/AC_QUEST.TP2  1  0 Installed
BST/SETUP-BST.TP2  0  0 Installed
BG1UB/SETUP-BG1UB.TP2  0  0 Installed
BG1UB/SETUP-BG1UB.TP2  0  1 Installed
BG1UB/SETUP-BG1UB.TP2  0  3 Installed
BG1UB/SETUP-BG1UB.TP2  0  4 Installed
BG1UB/SETUP-BG1UB.TP2  0  5 Installed
BG1UB/SETUP-BG1UB.TP2  0  6 Installed
BG1UB/SETUP-BG1UB.TP2  0  7 Installed
BG1UB/SETUP-BG1UB.TP2  0  8 Installed
BG1UB/SETUP-BG1UB.TP2  0  9 Installed
BG1UB/SETUP-BG1UB.TP2  0 10 Installed
BG1UB/SETUP-BG1UB.TP2  0 11 Installed
BG1UB/SETUP-BG1UB.TP2  0 12 Installed
BG1UB/SETUP-BG1UB.TP2  0 13 Installed
BG1UB/SETUP-BG1UB.TP2  0 14 Installed
BG1UB/SETUP-BG1UB.TP2  0 15 Installed
BG1UB/SETUP-BG1UB.TP2  0 16 Installed
BG1UB/SETUP-BG1UB.TP2  0 17 Installed
BG1UB/SETUP-BG1UB.TP2  0 18 Installed
BG1UB/SETUP-BG1UB.TP2  0 19 Installed
BG1UB/SETUP-BG1UB.TP2  0 20 Installed
BG1UB/SETUP-BG1UB.TP2  0 21 Installed
BG1UB/SETUP-BG1UB.TP2  0 22 Installed
BG1UB/SETUP-BG1UB.TP2  0 23 Installed
BG1UB/SETUP-BG1UB.TP2  0 24 Installed
BG1UB/SETUP-BG1UB.TP2  0 27 Installed
BG1UB/SETUP-BG1UB.TP2  0 28 Installed
BG1UB/SETUP-BG1UB.TP2  0 29 Installed
BG1UB/SETUP-BG1UB.TP2  0 31 Installed
BG1UB/SETUP-BG1UB.TP2  0 33 Installed
BG1UB/SETUP-BG1UB.TP2  0 34 Installed
FINCHNPC/FINCHNPC.TP2  0  0 Installed
VALERIE/VALERIE.TP2  0  0 Installed
GLAMNPCPACK/SETUP-GLAMNPCPACK.TP2  0  0 Installed
WHITE/WHITE.TP2  0  0 Installed
INDINPC/SETUP-INDINPC.TP2  0  0 Installed
SETUP-TENYATHERMIDOR.TP2  0  0 Installed
THALAN/THALAN.TP2  0  0 Installed
SETUP-LOSTITEMS.TP2  0  0 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  1 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  2 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  3 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0 301 Installed
SETUP-BGTTWEAK.TP2  0 400 Installed
SETUP-BGTTWEAK.TP2  0 500 Installed
SETUP-BGTTWEAK.TP2  0 901 Installed
SETUP-BGTTWEAK.TP2  0 1104 Installed
SETUP-BGTTWEAK.TP2  0 1200 Installed
SETUP-BGTTWEAK.TP2  0 1502 Installed
SETUP-BGTTWEAK.TP2  0 2300 Installed
SETUP-BGTTWEAK.TP2  0 2400 Installed
SETUP-BGTTWEAK.TP2  0 2500 Installed
SETUP-BGTTWEAK.TP2  0 2600 Installed
SETUP-BGTTWEAK.TP2  0 2700 Installed
BG_TRAVEL/SETUP-BG_TRAVEL.TP2  0 66 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  0 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  1 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  8 Installed
MIH_IP/SETUP-MIH_IP.TP2  0 11 Installed
VIC.TP2  0  0 Installed
NPCKIT/NPCKIT.TP2  0 30 Installed
NPCKIT/NPCKIT.TP2  0 31 Installed
NPCKIT/NPCKIT.TP2  0 1400 Installed
NPCKIT/NPCKIT.TP2  0 2300 Installed
NPCKIT/NPCKIT.TP2  0 2800 Installed
SETUP-OVERSIGHT.TP2  0  2 Installed
PHORD_DRUIDKITS/SETUP-PHORD_DRUIDKITS.TP2  0  0 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  0 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  1 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  2 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  3 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  4 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  5 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  6 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  7 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  8 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  9 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0 10 Installed
RR/SETUP-RR.TP2  0  0 Installed
RR/SETUP-RR.TP2  0  1 Installed
RR/SETUP-RR.TP2  0  3 Installed
RR/SETUP-RR.TP2  0  4 Installed
RR/SETUP-RR.TP2  0  6 Installed
RR/SETUP-RR.TP2  0  7 Installed
RR/SETUP-RR.TP2  0  8 Installed
RR/SETUP-RR.TP2  0  9 Installed
RR/SETUP-RR.TP2  0 999 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 12 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 13 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 15 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 1060 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2000 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2003 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2047 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2048 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4000 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4010 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4020 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5001 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5005 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5006 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5007 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5013 Installed
1PP/1PP.TP2  0 101 Installed
1PP/1PP.TP2  0 103 Installed
1PP/1PP.TP2  0 104 Installed
1PP/1PP.TP2  0 105 Installed
1PP/1PP.TP2  0 114 Installed
1PP/1PP.TP2  0 200 Installed
1PP/1PP.TP2  0 201 Installed
1PP/1PP.TP2  0 202 Installed
1PP/1PP.TP2  0 203 Installed
1PP/1PP.TP2  0 204 Installed
1PP/1PP.TP2  0 207 Installed
1PP/1PP.TP2  0 210 Installed
1PP/1PP.TP2  0 400 Installed
1PP/1PP.TP2  0 401 Installed
1PP/1PP.TP2  0 301 Installed

Install Component [Item Revisions by Demivrgvs]?
[I]nstall, or [N]ot Install or [Q]uit? 
Installing [Item Revisions by Demivrgvs] [V4 Beta 10 (Revised V1.3.430)]
loading 1 tra file
[item_rev/tobex_redist/TobEx.tra] has 5 translation strings
Copying and patching 1 file ...
[TobEx_ini/TobExVer.txt] loaded, 2 bytes

TobEx already up-to-date.
loading 1 tra file
[item_rev/languages/english/item_descriptions.tra] has 1869 translation strings
loading 1 tra file
[item_rev/languages/english/item_upgrades.tra] has 13 translation strings
loading 1 tra file
[item_rev/languages/english/potion_descriptions.tra] has 102 translation strings
loading 1 tra file
[item_rev/languages/english/item_descriptions.tra] has 1869 translation strings
loading 1 tra file
[item_rev/languages/english/item_upgrades.tra] has 13 translation strings
loading 1 tra file
[item_rev/languages/english/potion_descriptions.tra] has 102 translation strings

[item_rev/lib/compatibility.tpa] PARSE ERROR at line 59 column 1-109
Near Text: 1510
	GLR parse error

[item_rev/lib/compatibility.tpa]  ERROR at line 59 column 1-109
Near Text: 1510
	Parsing.Parse_error
ERROR: parsing [item_rev/lib/compatibility.tpa]: Parsing.Parse_error
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Item Revisions by Demivrgvs], rolling back to previous state
Unable to Unlink [item_rev/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "item_rev/backup/0/OTHER.0")
[item_rev/backup/0/UNSETSTR.0] SET_STRING uninstall info not found
Will uninstall   0 files for [ITEM_REV/ITEM_REV.TP2] component 0.
Uninstalled      0 files for [ITEM_REV/ITEM_REV.TP2] component 0.

[item_rev/lib/compatibility.tpa] PARSE ERROR at line 59 column 1-109
Near Text: 1510
	GLR parse error

[item_rev/lib/compatibility.tpa]  ERROR at line 59 column 1-109
Near Text: 1510
	Parsing.Parse_error
ERROR: parsing [item_rev/lib/compatibility.tpa]: Parsing.Parse_error
Error Uninstalling [ITEM_REV/ITEM_REV.TP2] component 0:
Parsing.Parse_error
TOBEX/TOBEX.TP2  0 100 Installed
TOBEX/TOBEX.TP2  0 101 Installed
TOBEX/TOBEX.TP2  0 102 Installed
TOBEX/TOBEX.TP2  0 105 Installed
TOBEX/TOBEX.TP2  0 109 Installed
TOBEX/TOBEX.TP2  0 111 Installed
TOBEX/TOBEX.TP2  0 113 Installed
TOBEX/TOBEX.TP2  0 114 Installed
TOBEX/TOBEX.TP2  0 115 Installed
TOBEX/TOBEX.TP2  0 116 Installed
TOBEX/TOBEX.TP2  0 117 Installed
TOBEX/TOBEX.TP2  0 118 Installed
TOBEX/TOBEX.TP2  0 119 Installed
TOBEX/TOBEX.TP2  0 120 Installed
TOBEX/TOBEX.TP2  0 121 Installed
TOBEX/TOBEX.TP2  0 122 Installed
TOBEX/TOBEX.TP2  0 123 Installed
TOBEX/TOBEX.TP2  0 124 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  0 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 1001 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0  3 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 101 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 103 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 110 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 111 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 112 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 113 Installed
BG2FIXPACK/SETUP-BG2FIXPACK.TP2  0 116 Installed
BGT/BGT.TP2  0  0 Installed
BGGRAPHICS/SETUP-BGGRAPHICS.TP2  0  0 Installed
RES_FIXER/SETUP-RES_FIXER.TP2  0  0 Installed
DSOTSC/DSOTSC.TP2  0  0 Installed
DSOTSC/DSOTSC.TP2  0  3 Installed
NTOTSC/NTOTSC.TP2  0  0 Installed
NTOTSC/NTOTSC.TP2  0  2 Installed
NTOTSC/NTOTSC.TP2  0  3 Installed
NTOTSC/NTOTSC.TP2  0  4 Installed
NTOTSC/NTOTSC.TP2  0  5 Installed
NTOTSC/NTOTSC.TP2  0  6 Installed
NTOTSC/NTOTSC.TP2  0  9 Installed
BGQE/SETUP-BGQE.TP2  0  0 Installed
BGQE/SETUP-BGQE.TP2  0  1 Installed
BGQE/SETUP-BGQE.TP2  0  2 Installed
BGQE/SETUP-BGQE.TP2  0  3 Installed
BGQE/SETUP-BGQE.TP2  0  4 Installed
BGQE/SETUP-BGQE.TP2  0  5 Installed
BGQE/SETUP-BGQE.TP2  0  6 Installed
BGQE/SETUP-BGQE.TP2  0  7 Installed
BGQE/SETUP-BGQE.TP2  0  8 Installed
BGQE/SETUP-BGQE.TP2  0  9 Installed
BGQE/SETUP-BGQE.TP2  0 10 Installed
BGQE/SETUP-BGQE.TP2  0 11 Installed
BGQE/SETUP-BGQE.TP2  0 12 Installed
BGQE/SETUP-BGQE.TP2  0 13 Installed
BGQE/SETUP-BGQE.TP2  0 14 Installed
BGQE/SETUP-BGQE.TP2  0 15 Installed
BGQE/SETUP-BGQE.TP2  0 16 Installed
SETUP-TGC1E.TP2  0  0 Installed
SIRINESCALL/SETUP-SIRINESCALL.TP2  0  0 Installed
SOA/SETUP-SOA.TP2  0  1 Installed
AC_QUEST/AC_QUEST.TP2  1  0 Installed
BST/SETUP-BST.TP2  0  0 Installed
BG1UB/SETUP-BG1UB.TP2  0  0 Installed
BG1UB/SETUP-BG1UB.TP2  0  1 Installed
BG1UB/SETUP-BG1UB.TP2  0  3 Installed
BG1UB/SETUP-BG1UB.TP2  0  4 Installed
BG1UB/SETUP-BG1UB.TP2  0  5 Installed
BG1UB/SETUP-BG1UB.TP2  0  6 Installed
BG1UB/SETUP-BG1UB.TP2  0  7 Installed
BG1UB/SETUP-BG1UB.TP2  0  8 Installed
BG1UB/SETUP-BG1UB.TP2  0  9 Installed
BG1UB/SETUP-BG1UB.TP2  0 10 Installed
BG1UB/SETUP-BG1UB.TP2  0 11 Installed
BG1UB/SETUP-BG1UB.TP2  0 12 Installed
BG1UB/SETUP-BG1UB.TP2  0 13 Installed
BG1UB/SETUP-BG1UB.TP2  0 14 Installed
BG1UB/SETUP-BG1UB.TP2  0 15 Installed
BG1UB/SETUP-BG1UB.TP2  0 16 Installed
BG1UB/SETUP-BG1UB.TP2  0 17 Installed
BG1UB/SETUP-BG1UB.TP2  0 18 Installed
BG1UB/SETUP-BG1UB.TP2  0 19 Installed
BG1UB/SETUP-BG1UB.TP2  0 20 Installed
BG1UB/SETUP-BG1UB.TP2  0 21 Installed
BG1UB/SETUP-BG1UB.TP2  0 22 Installed
BG1UB/SETUP-BG1UB.TP2  0 23 Installed
BG1UB/SETUP-BG1UB.TP2  0 24 Installed
BG1UB/SETUP-BG1UB.TP2  0 27 Installed
BG1UB/SETUP-BG1UB.TP2  0 28 Installed
BG1UB/SETUP-BG1UB.TP2  0 29 Installed
BG1UB/SETUP-BG1UB.TP2  0 31 Installed
BG1UB/SETUP-BG1UB.TP2  0 33 Installed
BG1UB/SETUP-BG1UB.TP2  0 34 Installed
FINCHNPC/FINCHNPC.TP2  0  0 Installed
VALERIE/VALERIE.TP2  0  0 Installed
GLAMNPCPACK/SETUP-GLAMNPCPACK.TP2  0  0 Installed
WHITE/WHITE.TP2  0  0 Installed
INDINPC/SETUP-INDINPC.TP2  0  0 Installed
SETUP-TENYATHERMIDOR.TP2  0  0 Installed
THALAN/THALAN.TP2  0  0 Installed
SETUP-LOSTITEMS.TP2  0  0 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  1 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  2 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0  3 Installed
KTWEAKS/SETUP-KTWEAKS.TP2  0 301 Installed
SETUP-BGTTWEAK.TP2  0 400 Installed
SETUP-BGTTWEAK.TP2  0 500 Installed
SETUP-BGTTWEAK.TP2  0 901 Installed
SETUP-BGTTWEAK.TP2  0 1104 Installed
SETUP-BGTTWEAK.TP2  0 1200 Installed
SETUP-BGTTWEAK.TP2  0 1502 Installed
SETUP-BGTTWEAK.TP2  0 2300 Installed
SETUP-BGTTWEAK.TP2  0 2400 Installed
SETUP-BGTTWEAK.TP2  0 2500 Installed
SETUP-BGTTWEAK.TP2  0 2600 Installed
SETUP-BGTTWEAK.TP2  0 2700 Installed
BG_TRAVEL/SETUP-BG_TRAVEL.TP2  0 66 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  0 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  1 Installed
MIH_IP/SETUP-MIH_IP.TP2  0  8 Installed
MIH_IP/SETUP-MIH_IP.TP2  0 11 Installed
VIC.TP2  0  0 Installed
NPCKIT/NPCKIT.TP2  0 30 Installed
NPCKIT/NPCKIT.TP2  0 31 Installed
NPCKIT/NPCKIT.TP2  0 1400 Installed
NPCKIT/NPCKIT.TP2  0 2300 Installed
NPCKIT/NPCKIT.TP2  0 2800 Installed
SETUP-OVERSIGHT.TP2  0  2 Installed
PHORD_DRUIDKITS/SETUP-PHORD_DRUIDKITS.TP2  0  0 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  0 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  1 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  2 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  3 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  4 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  5 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  6 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  7 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  8 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0  9 Installed
SONG_AND_SILENCE/SETUP-SONG_AND_SILENCE.TP2  0 10 Installed
RR/SETUP-RR.TP2  0  0 Installed
RR/SETUP-RR.TP2  0  1 Installed
RR/SETUP-RR.TP2  0  3 Installed
RR/SETUP-RR.TP2  0  4 Installed
RR/SETUP-RR.TP2  0  6 Installed
RR/SETUP-RR.TP2  0  7 Installed
RR/SETUP-RR.TP2  0  8 Installed
RR/SETUP-RR.TP2  0  9 Installed
RR/SETUP-RR.TP2  0 999 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 12 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 13 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 15 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 1060 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2000 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2003 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2047 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 2048 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4000 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4010 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 4020 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5001 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5005 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5006 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5007 Installed
SETUP-TURAMBAR_FIXES_TWEAKS.TP2  0 5013 Installed
1PP/1PP.TP2  0 101 Installed
1PP/1PP.TP2  0 103 Installed
1PP/1PP.TP2  0 104 Installed
1PP/1PP.TP2  0 105 Installed
1PP/1PP.TP2  0 114 Installed
1PP/1PP.TP2  0 200 Installed
1PP/1PP.TP2  0 201 Installed
1PP/1PP.TP2  0 202 Installed
1PP/1PP.TP2  0 203 Installed
1PP/1PP.TP2  0 204 Installed
1PP/1PP.TP2  0 207 Installed
1PP/1PP.TP2  0 210 Installed
1PP/1PP.TP2  0 400 Installed
1PP/1PP.TP2  0 401 Installed
1PP/1PP.TP2  0 301 Installed
ERROR: Parsing.Parse_error
Please submit a report regarding this problem, including the information contained in SETUP-ITEM_REV.DEBUG and look for support at: Demivrgvs, Ardanis and Mike1072 at forums.gibberlings3.net
Using Language [English]
[English] has 2 top-level TRA files
[item_rev/languages/english/setup.tra] has 60 translation strings
[item_rev/languages/english/description_updates.tra] has 173 translation strings

Install Component [Item Revisions by Demivrgvs]?
[I]nstall, or [N]ot Install or [Q]uit?

**Comment by BartyMae** [comment]
Hopefully already fixed - happened while in the middle of updating stuff today.
