### ISSUE TITLE
V1.3.478 errors out

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/IR_Revised#13]
[SETUP-ITEM_REV.txt](https://github.com/BartyMae/IR_Revised/files/6625635/SETUP-ITEM_REV.txt)

ERROR: error loading [item_rev/itm/dvdharm.spl]
Stopping installation because of error.
Stopping installation because of error.
Stopping installation because of error.

ERROR Installing [Item Revisions by Demivrgvs], rolling back to previous state
Unable to Unlink [item_rev/backup/0/OTHER.0]: Unix.Unix_error(1, "unlink", "item_rev/backup/0/OTHER.0")

**Comment by BartyMae** [comment]
Typo with "dvdcharm", fixed.

**Comment by ChitownWillie** [comment]
Thanks!
