### ISSUE TITLE
The Chelsey Crusher +2: Incorrect modifier type not reducing attacks per round by -1/2

### ISSUE THREAD

**Issue by AshLancer** [BartyMae/IR_Revised#18]
Hello Bart,

I've encountered another bug during gameplay. The description in IRR's The Chelsey Crusher +2 (HALB13.ITM) states that the weapon is supposed to reduce attacks per round by -1/2 while equipped, but the effect does nothing because of an incorrect modifier type set to -6, instead of 0.
![Untitled](https://github.com/user-attachments/assets/15d83acb-5cd1-4762-9b7e-a3f6ca3ae8a9)

**Comment by BartyMae** [comment]
Thanks, will look into it within the next couple of days and update when I've fixed it.

**Comment by BartyMae** [comment]
@AshLancer The fix was easy, re-setting up my Git client so that I could actually commit the fix to the repository was not so easy, but now I'm properly set up again, so that's taken care of. Thank you!

**Comment by AshLancer** [comment]
> @AshLancer The fix was easy, re-setting up my Git client so that I could actually commit the fix to the repository was not so easy, but now I'm properly set up again, so that's taken care of. Thank you!

Glad to have you back!!
